//models/Prescription.js
//updated Model

const mongoose = require("mongoose");

const rawMaterialDetailSchema = new mongoose.Schema({
  _id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "RawMaterial",
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  quantity: {
    type: Number,
    required: true,
    min: 0.1,
  },
  pricePerUnit: {
    type: Number,
    required: true,
    min: 0,
  },
  totalPrice: {
    type: Number,
    required: true,
    min: 0,
  },
});

// Updated standard schedule schema
const standardScheduleSchema = new mongoose.Schema({
  day: { type: Number, required: true },
  timing: {
    morning: {
      food: { type: String, enum: ["E/S", "L/S"], required: false },
      time: { type: String },
    },
    afternoon: {
      food: { type: String, enum: ["E/S", "L/S"], required: false },
      time: { type: String },
    },
    evening: {
      food: { type: String, enum: ["E/S", "L/S"], required: false },
      time: { type: String },
    },
    night: {
      food: { type: String, enum: ["E/S", "L/S"], required: false },
      time: { type: String },
    },
  },
});

// Updated frequent schedule schema with detailed frequency info
const frequentFrequencySchema = new mongoose.Schema({
  doses: { type: Number, required: true },
  hours: { type: Number, required: true },
  minutes: { type: Number, default: 0 },
});

const frequentScheduleSchema = new mongoose.Schema({
  day: { type: Number, required: true },
  frequency: { type: String, required: true }, // e.g. "2hr 0mins"
  frequentFrequency: frequentFrequencySchema,
});

// Parallel consumption schedule item schema
const parallelConsumptionScheduleItemSchema = new mongoose.Schema({
  day: { type: Number, required: true },
  doseNumber: { type: Number, required: true },
  time: { type: String, required: true }, // Time in HH:MM format
  medicineIndex: { type: Number, required: true },
  medicineName: { type: String, required: true },
  type: {
    type: String,
    enum: ["sequential", "parallel"],
    required: true,
  },
  sequentialOrder: { type: Number },
  parallelGroup: { type: Number },
  isOverlapping: { type: Boolean, default: false },
});

// Parallel consumption configuration schema
const parallelConsumptionSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ["sequential", "parallel"],
    required: true,
  },
  schedule: [parallelConsumptionScheduleItemSchema],
  autoGenerated: {
    type: Boolean,
    default: false,
  },
  medicineIndex: { type: Number, required: true },
  medicineName: { type: String, required: true },
  intervalHours: { type: Number, default: 0 },
  intervalMinutes: { type: Number, default: 0 },
  totalDoses: { type: Number, default: 1 },
  startTime: { type: String, default: "08:00" },
});

// Updated prescription item schema with complete frequency support
const prescriptionItemSchema = new mongoose.Schema({
  medicineName: {
    type: String,
    required: false,
  },
  rawMaterialDetails: [rawMaterialDetailSchema],
  form: {
    type: String,
    enum: ["Tablets", "Pills", "Liquid form", "Individual Medicine"],
    required: false,
  },
  uom: {
    type: String,
    enum: ["Graam", "Dram", "ML", "Pieces"],
    required: false,
  },
  dispenseQuantity: {
    type: String,
    required: false,
    min: 0.1,
  },
  duration: {
    type: String,
    required: false,
  },
  frequencyType: {
    type: String,
    enum: ["Standard", "Frequent", "standard", "frequent"],
    required: false,
  },
  // Store the complete frequency configuration
  frequencies: [
    {
      consumptionPattern: {
        type: String,
        enum: ["single", "parallel", "sequential"],
        required: true,
      },
      day: { type: Number, required: true },
      duration: { type: String, required: true },
      frequency: { type: String, required: false },
      frequencyType: {
        type: String,
        enum: ["standard", "frequent"],
        required: true,
      },
      isOverlapping: { type: Boolean, default: false },

      // For frequent frequencies
      frequentFrequency: {
        doses: { type: Number },
        hours: { type: Number },
        minutes: { type: Number, default: 0 },
      },

      // For standard frequencies
      standardFrequency: {
        morning: {
          foodType: { type: String, enum: ["E/S", "L/S"] },
          from: { type: String },
        },
        afternoon: {
          foodType: { type: String, enum: ["E/S", "L/S"] },
          from: { type: String },
        },
        evening: {
          foodType: { type: String, enum: ["E/S", "L/S"] },
          from: { type: String },
        },
        night: {
          foodType: { type: String, enum: ["E/S", "L/S"] },
          from: { type: String },
        },
      },

      // Parallel consumption data for this frequency
      parallelConsumption: {
        type: {
          type: String,
          enum: ["sequential", "parallel"],
          required: false,
        },
        schedule: [parallelConsumptionScheduleItemSchema],
        autoGenerated: { type: Boolean, default: false },
      },

      // Generated timings for frequent schedules
      timings: [{ type: String }], // Array of time strings like ["08:00", "10:00", "12:00"]
    },
  ],

  // Legacy fields for backward compatibility
  standardSchedule: [standardScheduleSchema],
  frequentSchedule: [frequentScheduleSchema],
  parallelConsumption: parallelConsumptionSchema,

  price: {
    type: Number,
    default: 0,
  },
  additionalComments: {
    type: String,
    default: "",
  },
  prescriptionType: {
    type: String,
    enum: [
      "Only Prescription",
      "Prescription + Medicine",
      "Medicine + Kit",
      "Only Medicine",
      "Prescription + Medicine kit",
      "SOS Medicine",
    ],
    required: true,
  },
  consumptionType: {
    type: String,
    enum: ["Sequential", "Sequential + Gap", "Parallel"],
    required: true,
  },
  medicineConsumption: {
    type: String,
    required: true,
  },
  label: {
    type: String,
    enum: ["A", "B", "C", "1", "2", "3", "4"],
    required: false,
  },
});

const prescriptionSchema = new mongoose.Schema({
  patientId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Patient",
    required: true,
  },
  doctorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Doctor",
    required: true,
  },
  appointmentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Appointment",
  },
  prescriptionItems: [prescriptionItemSchema],
  followUpDays: {
    type: Number,
    default: 10,
  },
  medicineCharges: {
    type: Number,
    default: 0,
  },
  isPayementDone: {
    type: Boolean,
    default: false,
  },
  shippingCharges: {
    type: Number,
    default: 0,
  },
  additionalCharges:{
    type:Number,
    default:0
  },
  trackingId: { 
    type: String, 
    default: null 
  },
  isProductReceived: { 
    type: Boolean, 
    default: null, 
    required:false 
  },
  isProductShipped: { 
    type: Boolean, 
    default: false 
  },
  shippedDate: {
  type: Date,
  default: null
  },
  startDate: { 
    type: Date, 
    required: false },
  endDate: { 
     type: Date,
     default: null },
  notes: {
    type: String,
  },
  specialNote:{
    type:String,
  },
  sendSpecialNote:{
    type:Boolean,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
  medicineCourse: {
    type: Number, // in days
    required: true,
  },
  action: {
    status: {
      type: String,
      enum: ["In Progress", "Close"],
      default: "In Progress",
      required: true,
    },
    closeComment: {
      type: String,
      default: "",
    },
  },
  closeComment: {
    type: String,
    default: null,
  },
  subPrescriptionID: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Prescription",
    },
  ],
  consultingType: {
    type: String,
  },
  consultingFor: {
    type: String,
  },
});

module.exports = mongoose.model("Prescription", prescriptionSchema);
